services:

  db1:
    networks:
      openfire-federated-net:
        ipv4_address: 172.50.0.11
        ipv6_address: fd23:d79:d076::11

  db2:
    networks:
      openfire-federated-net:
        ipv4_address: 172.50.0.21
        ipv6_address: fd23:d79:d076::21

  xmpp1:
    networks:
      openfire-federated-net:
        ipv4_address: 172.50.0.10
        ipv6_address: fd23:d79:d076::10
    extra_hosts:
      - "xmpp1.localhost.example=fd23:d79:d076::10"
      - "conference.xmpp1.localhost.example=fd23:d79:d076::10"
      - "xmpp2.localhost.example=fd23:d79:d076::20"
      - "conference.xmpp2.localhost.example=fd23:d79:d076::20"
      - "ocsp.localhost.example:[fd23:d79:d076::88]"

  xmpp2:
    networks:
      openfire-federated-net:
        ipv4_address: 172.50.0.20
        ipv6_address: fd23:d79:d076::20
    extra_hosts:
      - "xmpp1.localhost.example=fd23:d79:d076::10"
      - "conference.xmpp1.localhost.example=fd23:d79:d076::10"
      - "xmpp2.localhost.example=fd23:d79:d076::20"
      - "conference.xmpp2.localhost.example=fd23:d79:d076::20"
      - "ocsp.localhost.example:[fd23:d79:d076::88]"

networks:
  openfire-federated-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.50.0.0/24
        - subnet: fd23:0d79:d076::/64
